### ISSUE TITLE
fatal: repository 'https://github.com/fabiobjardim/bigdata_docker.git/' not found

### ISSUE THREAD

**Issue by manoelmarcos** [fabiogjardim/bigdata_docker#10]
Olá Fábio, tudo bem?

Tentei executar esse comando, de acordo com as instruções em sua página em: https://github.com/fabiogjardim/bigdata_docker  mas não funcionou:

C:\docker>git clone http://github.com/fabiobjardim/bigdata_docker.git
Cloning into 'bigdata_docker'...
info: please complete authentication in your browser...
remote: Repository not found.
**fatal: repository 'https://github.com/fabiobjardim/bigdata_docker.git/' not found**

**Comment by mbiombani** [comment]
try 

git clone https://github.com/fabiogjardim/bigdata_docker.git

**Comment by mateusvalente** [comment]
Eu tenho erro au tentar executar o jupyter

| Traceback (most recent call last):
jupyter-spark              |   File "/opt/anaconda3/bin/jupyter", line 4, in <module>
jupyter-spark              |     import re
jupyter-spark              |   File "/opt/anaconda3/lib/python3.6/re.py", line 122, in <module>
jupyter-spark              |     import enum
jupyter-spark              |   File "/opt/anaconda3/lib/python3.6/enum.py", line 2, in <module>
jupyter-spark              |     from types import MappingProxyType, DynamicClassAttribute
jupyter-spark              | ImportError: cannot import name 'MappingProxyType'
